version: '3.8'

services:
  hot-wallet-db:
    image: postgres:15
    env_file: .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "15432:5432"

  app:
    image: hot-wallet:latest
    env_file: .env
    build: .
    environment:
      DB_URL: ${DB_URL}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DEPOSIT_DELAY_MS: ${DEPOSIT_DELAY_MS}
      WITHDRAWAL_DELAY_MS: ${WITHDRAWAL_DELAY_MS}
      DB_ISOLATION: ${DB_ISOLATION}
    ports:
      - "8080:8080"
    depends_on:
      - hot-wallet-db
