spring:
  application:
    name: hot_wallet
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: always
  liquibase:
    default-schema: public
    change-log: classpath:/db/changelog/db.changelog-master.yaml
    enabled: true
  jpa:
    properties:
      hibernate.connection.isolation: ${DB_ISOLATION:2}
hot-wallet:
  batch:
    deposit-delay-ms: ${DEPOSIT_DELAY_MS}
    withdrawal-delay-ms: ${WITHDRAWAL_DELAY_MS}

